### ISSUE TITLE
Uncaught ReferenceError: ApiAIPlugin is not defined

### ISSUE THREAD

**Issue by riyer15** [xVir/api-ai-ionic-sample#1]
I get this error when ApiAIPlugin.init is declared, and it occurs when I run this code and when I run my own ionic app (and try to integrate APIai). Do you know what I should do? I tried all the solutions suggested at (https://github.com/api-ai/api-ai-cordova/issues/7) but none worked. @xVir thanks!

**Comment by riyer15** [comment]
I just found the solution, it was to wrap the ApiAiplugin.init in a `$ionicPlatform.ready(function() {}` block.  Also, Ionic serve (the webserver emulator) cannot access cordova plugins, so you must use an ios or android emulator.

**Comment by xVir** [comment]
Hi, @riyer15 

Thanks for information!

So, there is no need to change sample? https://github.com/xVir/api-ai-ionic-sample/blob/master/www/js/app.js#L11

Thanks.
